import type { VoicemailItem } from '@/types/voicemail'

export const MOCK_VOICEMAILS: VoicemailItem[] = [
  {
    id: 'vm-001',
    callerName: 'Dorothy Lim',
    callerNumber: '0412345678',
    receivedAt: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    duration: 87,
    location: 'Clinic 1',
    urgency: 'urgent',
    urgencyConfidence: 0.97,
    intent: 'symptom-acute',
    summary: 'Chest tightness and shortness of breath since last night. Feels worse this morning. History of hypertension.',
    keyDetails: [
      'Symptom: chest tightness + shortness of breath',
      'Onset: last night, worsening this morning',
      'PMH: hypertension (on medication)',
      'Requests urgent same-day appointment',
    ],
    suggestedAction: 'Call back immediately — triage for same-day urgent appointment or advise 000 if symptoms worsen.',
    transcriptExcerpt: '"Hi, this is Dorothy Lim... I\'ve been having this tight feeling in my chest since last night and it\'s not going away. I\'m finding it a bit hard to breathe deeply. I have high blood pressure, I\'m on medication for it, so I\'m a bit worried. Could someone please call me back as soon as possible, I\'d really like to come in today if I can."',
    flagForHuman: true,
    status: 'new',
    statusHistory: [],
  },
  {
    id: 'vm-002',
    callerName: 'Emma Davis',
    callerNumber: '0487654321',
    receivedAt: new Date(Date.now() - 1000 * 60 * 42).toISOString(),
    duration: 65,
    location: 'Clinic 1',
    urgency: 'urgent',
    urgencyConfidence: 0.94,
    intent: 'symptom-acute',
    summary: '7-month-old with fever 39.4°C for 18 hours, not feeding well, very unsettled. Parent concerned.',
    keyDetails: [
      'Patient: infant, 7 months old',
      'Fever: 39.4°C for 18 hours',
      'Not feeding — reduced wet nappies',
      'Very unsettled, hard to console',
    ],
    suggestedAction: 'Priority callback — urgent appointment today. Advise paracetamol dosing if not already given.',
    transcriptExcerpt: '"Hi, I\'m calling about my baby, she\'s 7 months old, her name is Ella... she\'s had a temperature of 39.4 since yesterday afternoon and she\'s not feeding properly and she\'s been really crying a lot. I\'m quite worried, could someone call me back please, we\'re at Labrador."',
    flagForHuman: true,
    status: 'new',
    statusHistory: [],
  },
  {
    id: 'vm-003',
    callerName: 'Aisha Mohammed',
    callerNumber: '0455123456',
    receivedAt: new Date(Date.now() - 1000 * 60 * 71).toISOString(),
    duration: 112,
    location: 'Clinic 1',
    urgency: 'high',
    urgencyConfidence: 0.89,
    intent: 'mental-health',
    summary: 'Feels overwhelmed and not coping. Having dark thoughts but denies active suicidal plan. Requests urgent appointment.',
    keyDetails: [
      'Presenting: overwhelmed, not coping',
      'Dark thoughts — no active plan disclosed',
      'Requests appointment with usual GP, Dr Zhang',
      'SENSITIVE — handle with care',
    ],
    suggestedAction: 'Flag for GP review before callback. Same-day or next-day appointment with Dr Zhang.',
    transcriptExcerpt: '"Hi... I\'m a patient of Dr Zhang. I\'m really not doing well at the moment. I\'ve been feeling really low and I\'m having some dark thoughts. I don\'t have a plan or anything like that but I just really need to see someone soon. Please can you call me back."',
    flagForHuman: true,
    status: 'new',
    statusHistory: [],
  },
  {
    id: 'vm-004',
    callerName: 'Mike Santos',
    callerNumber: '0423987654',
    receivedAt: new Date(Date.now() - 1000 * 60 * 95).toISOString(),
    duration: 48,
    location: 'Clinic 2',
    urgency: 'high',
    urgencyConfidence: 0.91,
    intent: 'rx-refill',
    summary: 'Lipitor 40mg script running out today. No repeats remaining. On medication for 3 years, no recent review.',
    keyDetails: [
      'Medication: Lipitor 40mg (atorvastatin)',
      'Urgency: running out today — no repeats',
      'Last review: over 12 months ago',
      'Requests script only, no appointment needed',
    ],
    suggestedAction: 'GP to authorise emergency repeat or schedule phone review. Do not let lapse — cardiovascular risk.',
    transcriptExcerpt: '"Hi this is Mike Santos, patient number is… anyway I\'m ringing about my Lipitor, the 40mg one. I\'ve run out of repeats and I only have enough for today. I\'ve been on it for years, Dr Patel always just renews it. Could someone organise a script for me please, I don\'t really need to come in."',
    flagForHuman: false,
    status: 'new',
    statusHistory: [],
  },
  {
    id: 'vm-005',
    callerName: 'Priya Sharma',
    callerNumber: '0431567890',
    receivedAt: new Date(Date.now() - 1000 * 60 * 130).toISOString(),
    duration: 73,
    location: 'Clinic 2',
    urgency: 'high',
    urgencyConfidence: 0.88,
    intent: 'results',
    summary: 'Calling about blood test results from last week. GP left message that some results were abnormal. Patient anxious.',
    keyDetails: [
      'Awaiting: blood test results from last week',
      'GP left message — "some results abnormal"',
      'Patient anxious — did not get details',
      'Requesting clarification and appointment',
    ],
    suggestedAction: 'Pull results. GP to review and call back directly given abnormal flag — do not relay via reception.',
    transcriptExcerpt: '"Hello, my name is Priya Sharma. Dr O\'Connor left me a message yesterday saying some of my blood tests came back abnormal and I should call the clinic. I\'m a bit worried, I don\'t know which tests or what it means. Could someone please call me back and let me know what\'s happening?"',
    flagForHuman: true,
    status: 'in-progress',
    statusHistory: [
      { status: 'in-progress', changedAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(), changedBy: 'Sarah K.', note: 'Pulled results — waiting for Dr O\'Connor to review' },
    ],
    assignedTo: 'Sarah K.',
  },
  {
    id: 'vm-006',
    callerName: 'Robert Chen',
    callerNumber: '0467234567',
    receivedAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    duration: 34,
    location: 'Clinic 2',
    urgency: 'normal',
    urgencyConfidence: 0.95,
    intent: 'symptom-routine',
    summary: 'Persistent cough for 3 weeks. No fever. No shortness of breath. Wants appointment to get it checked.',
    keyDetails: [
      'Symptom: cough, 3 weeks duration',
      'No fever, no SOB, no haemoptysis',
      'Non-smoker',
      'Flexible on appointment timing',
    ],
    suggestedAction: 'Book routine appointment within 3–5 days.',
    transcriptExcerpt: '"Hi, I\'m Robert Chen, I\'ve had this cough for about three weeks now and it\'s not going away. I don\'t have a fever or anything serious, just the cough. I was hoping I could come in to get it looked at. I\'m pretty flexible on timing."',
    flagForHuman: false,
    status: 'new',
    statusHistory: [],
  },
  {
    id: 'vm-007',
    callerName: 'Sarah O\'Brien',
    callerNumber: '0412765432',
    receivedAt: new Date(Date.now() - 1000 * 60 * 210).toISOString(),
    duration: 41,
    location: 'Clinic 3',
    urgency: 'normal',
    urgencyConfidence: 0.96,
    intent: 'rx-refill',
    summary: 'Metformin 500mg script needs renewal. 2 repeats remain. Due for annual diabetes review.',
    keyDetails: [
      'Medication: Metformin 500mg',
      'Has 2 repeats remaining — not urgent yet',
      'Due for annual diabetes review (overdue)',
      'Prefers appointment with Dr Nguyen',
    ],
    suggestedAction: 'Book routine appointment + diabetes review with Dr Nguyen. Script can wait for consult.',
    transcriptExcerpt: '"Hello, this is Sarah O\'Brien calling about my Metformin script. I still have a couple of repeats left but I\'m coming up to needing a renewal soon. I know I\'m also due for my diabetes check-up so maybe I should just come in and do both? I\'d like to see Dr Nguyen if she\'s available."',
    flagForHuman: false,
    status: 'new',
    statusHistory: [],
  },
  {
    id: 'vm-008',
    callerName: 'Tom Walsh',
    callerNumber: '0445678901',
    receivedAt: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    duration: 55,
    location: 'Clinic 3',
    urgency: 'normal',
    urgencyConfidence: 0.93,
    intent: 'referral',
    summary: 'Requesting referral to cardiologist. Has private health. Saw Dr Patel 2 weeks ago who mentioned referral.',
    keyDetails: [
      'Referral to: cardiologist',
      'Discussed with Dr Patel ~2 weeks ago',
      'Has private health insurance',
      'Wants referral before next appointment in 6 weeks',
    ],
    suggestedAction: 'Check Dr Patel\'s notes — if referral agreed, generate and send to patient. No appointment needed.',
    transcriptExcerpt: '"Hi, Tom Walsh here. I saw Dr Patel a couple of weeks ago and he said he\'d refer me to a cardiologist. I\'ve got private health and I\'d like to get that sorted sooner rather than later. Could you organise the referral letter? I don\'t think I need to come in again for it."',
    flagForHuman: false,
    status: 'new',
    statusHistory: [],
  },
  {
    id: 'vm-009',
    callerName: 'Linda Park',
    callerNumber: '0478345678',
    receivedAt: new Date(Date.now() - 1000 * 60 * 295).toISOString(),
    duration: 29,
    location: 'Clinic 3',
    urgency: 'normal',
    urgencyConfidence: 0.97,
    intent: 'med-cert',
    summary: 'Needs backdated medical certificate for Monday and Tuesday absence. Saw clinic on Monday.',
    keyDetails: [
      'Request: backdated med cert (Mon–Tue)',
      'Was seen at clinic on Monday',
      'Employer requires certificate by end of week',
      'Email address: linda.park@gmail.com',
    ],
    suggestedAction: 'Check Monday consultation notes — if appropriate, issue med cert and email to patient.',
    transcriptExcerpt: '"Hi, Linda Park here. I came in on Monday and I was off work Monday and Tuesday. My boss needs a medical certificate and I forgot to ask for one when I was there. Could you send it through to my email? It\'s linda.park@gmail.com. Thanks."',
    flagForHuman: false,
    status: 'done',
    statusHistory: [
      { status: 'done', changedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(), changedBy: 'Admin', note: 'Med cert emailed' },
    ],
  },
  {
    id: 'vm-010',
    callerName: 'James Kwan',
    callerNumber: '0434567890',
    receivedAt: new Date(Date.now() - 1000 * 60 * 340).toISOString(),
    duration: 22,
    location: 'Clinic 1',
    urgency: 'low',
    urgencyConfidence: 0.99,
    intent: 'appt-change',
    summary: 'Cancelling appointment on Thursday at 2pm. No rebooking needed at this time.',
    keyDetails: [
      'Cancelling: Thursday 2:00pm appointment',
      'No rebooking requested',
      'Reason: work conflict',
      'Will call to rebook when available',
    ],
    suggestedAction: 'Cancel Thursday 2pm slot — free it for same-day bookings.',
    transcriptExcerpt: '"Hi, James Kwan calling. I need to cancel my appointment on Thursday afternoon at 2 o\'clock. Sorry for the short notice, work thing came up. I don\'t need to rebook right now, I\'ll call back when I know my schedule. Thanks."',
    flagForHuman: false,
    status: 'done',
    statusHistory: [
      { status: 'done', changedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(), changedBy: 'Admin', note: 'Appointment cancelled in Best Practice' },
    ],
  },
  {
    id: 'vm-011',
    callerName: 'Helen Nguyen',
    callerNumber: '0456789012',
    receivedAt: new Date(Date.now() - 1000 * 60 * 390).toISOString(),
    duration: 44,
    location: 'Clinic 2',
    urgency: 'low',
    urgencyConfidence: 0.92,
    intent: 'appt-book',
    summary: 'New patient inquiry. Wants to register with practice. Specifically requesting female GP. No urgency.',
    keyDetails: [
      'New patient — not currently registered',
      'Requesting: female GP preferred',
      'Condition: routine / new to area',
      'Contact: helen.nguyen84@hotmail.com',
    ],
    suggestedAction: 'Call back to gather Medicare details and book new patient appointment with Dr Nguyen or Dr Zhang.',
    transcriptExcerpt: '"Hi there, my name is Helen Nguyen. I\'ve just moved to the area and I\'m looking for a new GP. I don\'t have any urgent health issues, I just need to register somewhere. If possible I\'d prefer a female doctor. Could someone give me a call back? Thanks so much."',
    flagForHuman: false,
    status: 'new',
    statusHistory: [],
  },
  {
    id: 'vm-012',
    callerName: 'David Morris',
    callerNumber: '0489012345',
    receivedAt: new Date(Date.now() - 1000 * 60 * 420).toISOString(),
    duration: 31,
    location: 'Clinic 3',
    urgency: 'low',
    urgencyConfidence: 0.96,
    intent: 'admin',
    summary: 'Requesting update to phone number on file. Old number no longer active.',
    keyDetails: [
      'Request: update contact number on file',
      'Old number: no longer active',
      'New number: 0489012345 (this call)',
      'No clinical concern',
    ],
    suggestedAction: 'Update patient contact number in Best Practice. No callback needed — SMS confirmation.',
    transcriptExcerpt: '"Hello, David Morris here, date of birth 15th March 1962. I just wanted to let you know my old phone number is no longer active and this is my new number. Could you update it in your system please? No urgency, just an admin thing. Thanks."',
    flagForHuman: false,
    status: 'new',
    statusHistory: [],
  },
]

export interface VoicemailStats {
  total: number
  urgent: number
  high: number
  flagged: number
  needsAction: number
  clinic1: number
  clinic2: number
  clinic3: number
}

export function getStats(items: VoicemailItem[]): VoicemailStats {
  const active = items.filter(v => v.status !== 'done')
  return {
    total: active.length,
    urgent: active.filter(v => v.urgency === 'urgent').length,
    high: active.filter(v => v.urgency === 'high').length,
    flagged: active.filter(v => v.flagForHuman).length,
    needsAction: active.filter(v => v.status === 'new').length,
    clinic1: active.filter(v => v.location === 'Clinic 1').length,
    clinic2: active.filter(v => v.location === 'Clinic 2').length,
    clinic3: active.filter(v => v.location === 'Clinic 3').length,
  }
}
